name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set sha_short
        id: vars
        run: |-
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          # Set default branch name for PRs, as we still want to test build an image on PRs
          # but we have no branch to set a tag for.
          branch="test"
          if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
            branch="${GITHUB_REF#refs/heads/}"
          fi
          echo "branch=${branch}" >> $GITHUB_ENV
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.106.0'
      - name: Build
        run: hugo --minify
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }}
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.25.3'
      - name: Create Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - name: Set Image
        run: |
          kubectl set image -n blog deployment/blog blog=${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }}
      - name: Wait for deployment
        run: |
          kubectl rollout status -n blog deployment/blog