name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set sha_short
      id: vars
      run: |-
        echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        # Set default branch name for PRs, as we still want to test build an image on PRs
        # but we have no branch to set a tag for.
        branch="test"
        if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
          branch="${GITHUB_REF#refs/heads/}"
        fi
        echo "branch=${branch}" >> $GITHUB_ENV
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.106.0'
    - name: Build
      run: hugo --minify
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Container Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }}
    - name: Checkout Gitops Repo
      uses: actions/checkout@v2
      with:
        repository: dhawton/personal-gitops
        token: ${{ secrets.GITOPS_TOKEN }}
        path: gitops
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops/blog
        git config user.name "dhawton"
        git config user.email "daniel@hawton.org"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update image
      run: |
        cd $GITHUB_WORKSPACE/gitops/blog/base
        kustomize edit set image daniel/blog=${{ secrets.DOCKER_USERNAME }}/blog:${{ env.sha_short }}
    - name: Commit manifests
      run: |
        cd $GITHUB_WORKSPACE/gitops/blog
        git add .
        git commit -m "Update manifests"
    - name: Push to gitops repo
      run: |
        cd $GITHUB_WORKSPACE/gitops/blog
        git push origin main
